# Generated by Django 5.1.4 on 2026-09-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritePost',
        ),
    ]
