# Generated by Django 5.1.4 on 2026-09-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
        ('favorites', '0002_delete_favoritepost'),
        ('portfolios', '0002_migrate_cover_and_remove_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='portfolios.portfolio', verbose_name='نمونه\u200cکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_portfolios', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '❤️ علاقه\u200cمندی به نمونه\u200cکار',
                'verbose_name_plural': '❤️ علاقه\u200cمندی\u200cها به نمونه\u200cکارها',
                'db_table': 'favorite_portfolios',
                'unique_together': {('user', 'portfolio')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='explore.explorepost', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '❤️ علاقه\u200cمندی به پست',
                'verbose_name_plural': '❤️ علاقه\u200cمندی\u200cها به پست\u200cها',
                'db_table': 'favorite_posts',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
