# Generated by Django 5.1.4 on 2026-09-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'سوپر ادمین'), ('app_admin', 'ادمین اپلیکیشن'), ('content_admin', 'ادمین محتوا'), ('financial_admin', 'ادمین مالی'), ('support_admin', 'پشتیبانی')], max_length=50, unique=True, verbose_name='نام نقش')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='لیست دسترسی\u200cها', verbose_name='دسترسی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🎭 نقش ادمین',
                'verbose_name_plural': '🎭 نقش\u200cهای ادمین',
                'db_table': 'admin_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='dashboard.adminrole', verbose_name='نقش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '👨\u200d💼 ادمین',
                'verbose_name_plural': '👨\u200d💼 ادمین\u200cها',
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
