# Generated by Django 5.1.4 on 2026-09-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_action_4a51ed_idx',
            old_name='dash_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='dashboard_a_admin_p_a1a7bd_idx',
            old_name='dash_audit_admin_idx',
        ),
    ]
