# Generated by Django 5.1.4 on 2026-08-12 06:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام کسب\u200cوکار')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس')),
                ('working_hours', models.CharField(blank=True, default='', max_length=100, verbose_name='ساعات کاری')),
                ('about', models.TextField(blank=True, default='', verbose_name='درباره کسب\u200cوکار')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='businesses/covers/', verbose_name='تصویر کاور')),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='businesses/owners/', verbose_name='عکس مالک')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='لوگو')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='موقعیت جغرافیایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='دلیل رد')),
                ('national_id', models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی')),
                ('verified_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام تایید شده')),
                ('is_national_id_verified', models.BooleanField(default=False, verbose_name='کد ملی تایید شده')),
                ('bank_owner_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام صاحب حساب')),
                ('bank_national_id', models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی صاحب حساب')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام بانک')),
                ('bank_id', models.CharField(blank=True, default='', max_length=20, verbose_name='شناسه بانک')),
                ('bank_sheba', models.CharField(blank=True, default='', max_length=26, verbose_name='شماره شبا')),
                ('bank_card_number', models.CharField(blank=True, default='', max_length=16, verbose_name='شماره کارت')),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30, verbose_name='شماره حساب')),
                ('bank_info_registered', models.BooleanField(default=False, verbose_name='اطلاعات بانکی ثبت شده')),
                ('bank_info_verified', models.BooleanField(default=False, verbose_name='اطلاعات بانکی تایید شده')),
                ('booking_slug', models.SlugField(unique=True, verbose_name='اسلاگ رزرو')),
                ('booking_link_clicks', models.IntegerField(default=0, verbose_name='کلیک\u200cهای لینک رزرو')),
                ('booking_link_bookings', models.IntegerField(default=0, verbose_name='رزروهای لینک رزرو')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='میانگین امتیاز')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('vip_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای VIP')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='categories.businesscategory', verbose_name='نوع کسب\u200cوکار')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='شهر')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': '🏪 کسب\u200cوکار',
                'verbose_name_plural': '🏪 کسب\u200cوکارها',
                'db_table': 'businesses',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='businesses/gallery/', verbose_name='تصویر')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': '🖼️ تصویر گالری',
                'verbose_name_plural': '🖼️ گالری تصاویر',
                'db_table': 'business_gallery',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'city'], name='businesses_status_9488b6_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['province', 'city'], name='businesses_provinc_ba6194_idx'),
        ),
    ]
