# Generated by Django 5.1.4 on 2026-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
