# Generated by Django 5.1.4 on 2026-08-12 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(db_index=True, help_text='شماره موبایل ۱۱ رقمی (مثال: 09123456789)', max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='عکس پروفایل')),
                ('national_id', models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی')),
                ('is_national_id_verified', models.BooleanField(default=False, verbose_name='کد ملی تایید شده')),
                ('verified_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام تایید شده (از استعلام)')),
                ('is_verified', models.BooleanField(default=False, help_text='آیا شماره موبایل با OTP تایید شده؟', verbose_name='حساب تایید شده')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی به پنل ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر ارشد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '👤 کاربر',
                'verbose_name_plural': '👤 کاربران',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=5, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('change_phone', 'تغییر شماره'), ('booking_verify', 'تایید رزرو')], default='login', max_length=20, verbose_name='هدف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': '🔑 کد تایید',
                'verbose_name_plural': '🔑 کدهای تایید',
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose'], name='otp_codes_phone_886067_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('ios', 'آیفون'), ('android', 'اندروید'), ('desktop', 'دسکتاپ')], max_length=20, verbose_name='نوع دستگاه')),
                ('os_info', models.CharField(max_length=100, verbose_name='اطلاعات سیستم\u200cعامل')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی\u200cپی')),
                ('location', models.CharField(max_length=100, verbose_name='موقعیت')),
                ('is_current', models.BooleanField(default=False, verbose_name='دستگاه فعلی')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '📱 دستگاه فعال',
                'verbose_name_plural': '📱 دستگاه\u200cهای فعال',
                'db_table': 'user_devices',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='کد معرف')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='معرف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '🎫 کد معرف',
                'verbose_name_plural': '🎫 کدهای معرف',
                'db_table': 'user_referrals',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
