# Generated by Django 5.1.4 on 2026-07-26 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, help_text='شماره موبایل ۱۱ رقمی (مثال: 09123456789)', max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('business_owner', 'صاحب کسب\u200cوکار'), ('app_staff', 'کارمند اپ (پشتیبان)'), ('app_admin', 'ادمین بک\u200cاند اپ'), ('landing_admin', 'ادمین سایت معرفی'), ('super_admin', 'مدیر ارشد')], db_index=True, default='customer', max_length=20, verbose_name='نقش')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام و نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='عکس پروفایل')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('national_id_verified', models.BooleanField(default=False, verbose_name='کد ملی تایید شده')),
                ('verified_name', models.CharField(blank=True, default='', max_length=150, verbose_name='نام تایید شده (از استعلام)')),
                ('is_verified', models.BooleanField(default=False, help_text='آیا شماره موبایل با OTP تایید شده؟', verbose_name='حساب تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی به پنل ادمین')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('theme', models.CharField(choices=[('light', 'روشن'), ('dark', 'تاریک'), ('system', 'خودکار')], default='system', max_length=10, verbose_name='تم اپلیکیشن')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='اعلان\u200cها فعال')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '👤 کاربر',
                'verbose_name_plural': '👤 کاربران',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ActiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android', 'اندروید'), ('ios', 'آیفون'), ('web', 'وب')], default='android', max_length=10, verbose_name='نوع دستگاه')),
                ('device_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام دستگاه')),
                ('os_version', models.CharField(blank=True, default='', max_length=50, verbose_name='نسخه سیستم\u200cعامل')),
                ('app_version', models.CharField(blank=True, default='', max_length=20, verbose_name='نسخه اپلیکیشن')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='موقعیت')),
                ('is_trusted', models.BooleanField(default=True, verbose_name='مورد اعتماد')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '📱 دستگاه فعال',
                'verbose_name_plural': '📱 دستگاه\u200cهای فعال',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('change_phone', 'تغییر شماره'), ('verify_national_id', 'تایید کد ملی'), ('reset_password', 'بازیابی رمز عبور')], default='login', max_length=20, verbose_name='هدف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='حداکثر تلاش')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '🔑 کد تایید',
                'verbose_name_plural': '🔑 کدهای تایید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='accounts_cu_phone_c30b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['national_id'], name='accounts_cu_nationa_a453c6_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'purpose', '-created_at'], name='accounts_ot_phone_39ef5f_idx'),
        ),
    ]
