# Generated by Django 5.1.4 on 2026-08-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'ورود'), ('change_phone', 'تغییر شماره'), ('booking_verify', 'تایید رزرو'), ('delete_account', 'حذف حساب')], default='login', max_length=20, verbose_name='هدف'),
        ),
        migrations.CreateModel(
            name='UserBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام بانک')),
                ('bank_id', models.CharField(blank=True, default='', max_length=20, verbose_name='شناسه بانک')),
                ('sheba', models.CharField(blank=True, default='', max_length=26, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, default='', max_length=16, verbose_name='شماره کارت')),
                ('owner_name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام صاحب حساب')),
                ('is_complete', models.BooleanField(default=False, verbose_name='اطلاعات کامل است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '🏦 اطلاعات بانکی کاربر',
                'verbose_name_plural': '🏦 اطلاعات بانکی کاربران',
                'db_table': 'user_bank_info',
            },
        ),
    ]
