# Generated by Django 5.1.4 on 2026-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_purpose_userbankinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'ورود'), ('admin_login', 'ورود پنل مدیریت'), ('change_phone', 'تغییر شماره'), ('booking_verify', 'تایید رزرو'), ('delete_account', 'حذف حساب')], default='login', max_length=20, verbose_name='هدف'),
        ),
    ]
