# Generated by Django 5.1.4 on 2026-09-09 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_legacy_role_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='کاربر تعلیق\u200cشده می\u200cتواند لاگین کند اما دسترسی به APIها ندارد', verbose_name='تعلیق شده (تخلف)'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تعلیق'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(blank=True, help_text='ادمینی که کاربر را تعلیق کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL, verbose_name='تعلیق\u200cکننده'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, default='', help_text='دلیلی که ادمین برای تعلیق کاربر ثبت کرده است', verbose_name='دلیل تعلیق'),
        ),
    ]
