# Generated by Django 5.1.4 on 2026-08-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': '🏪 نوع کسب\u200cوکار',
                'verbose_name_plural': '🏪 انواع کسب\u200cوکار',
                'db_table': 'business_categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('icon_name', models.CharField(help_text='نام آیکون برای فرانت', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#A88B7D', max_length=7, verbose_name='رنگ')),
                ('gradient_start', models.CharField(default='#A88B7D', max_length=7, verbose_name='رنگ گرادیانت شروع')),
                ('gradient_end', models.CharField(default='#8D7468', max_length=7, verbose_name='رنگ گرادیانت پایان')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': '🏷️ دسته\u200cبندی خدمات',
                'verbose_name_plural': '🏷️ دسته\u200cبندی\u200cهای خدمات',
                'db_table': 'service_categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('type_id', models.CharField(help_text='شناسه برای فرانت', max_length=50, verbose_name='شناسه برای فرانت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='categories.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': '📂 زیرخدمت',
                'verbose_name_plural': '📂 زیرخدمات',
                'db_table': 'sub_services',
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
