# Generated by Django 5.1.4 on 2026-08-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, default='', max_length=300, verbose_name='توضیحات')),
                ('original_price', models.BigIntegerField(verbose_name='قیمت اصلی (تومان)')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('has_deposit', models.BooleanField(default=False, verbose_name='نیاز به بیعانه')),
                ('deposit_amount', models.BigIntegerField(default=0, verbose_name='مبلغ بیعانه (تومان)')),
                ('duration', models.IntegerField(default=60, verbose_name='مدت زمان (دقیقه)')),
                ('renewal_days', models.IntegerField(default=0, verbose_name='یادآوری تمدید (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='categories.servicecategory', verbose_name='دسته\u200cبندی')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='categories.subservice', verbose_name='زیرخدمت')),
            ],
            options={
                'verbose_name': '💆 خدمت',
                'verbose_name_plural': '💆 خدمات',
                'db_table': 'services',
                'ordering': ['business', 'name'],
            },
        ),
    ]
