# Generated by Django 5.1.4 on 2026-08-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('rose', 'صورتی پاستلی'), ('gold', 'طلایی لوکس'), ('mint', 'سبز مینیمال'), ('classic', 'کلاسیک')], default='classic', max_length=20, verbose_name='تم ظاهری')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': '📋 لیست قیمت',
                'verbose_name_plural': '📋 لیست\u200cهای قیمت',
                'db_table': 'price_lists',
            },
        ),
        migrations.CreateModel(
            name='PriceListNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100, verbose_name='عنوان')),
                ('min_value', models.IntegerField(default=0, verbose_name='حداقل')),
                ('max_value', models.IntegerField(default=0, verbose_name='حداکثر')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='services.pricelist', verbose_name='لیست قیمت')),
            ],
            options={
                'verbose_name': '📝 یادداشت لیست قیمت',
                'verbose_name_plural': '📝 یادداشت\u200cهای لیست قیمت',
                'db_table': 'price_list_notes',
                'ordering': ['created_at'],
            },
        ),
    ]
