# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_service_date', models.CharField(max_length=10, verbose_name='تاریخ انجام خدمت')),
                ('due_date', models.CharField(max_length=10, verbose_name='تاریخ موعد تمدید')),
                ('days_remaining', models.IntegerField(verbose_name='روزهای باقی\u200cمانده')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شده')),
                ('sent_date', models.CharField(blank=True, default='', max_length=10, verbose_name='تاریخ ارسال')),
                ('has_new_booking_after_send', models.BooleanField(default=False, verbose_name='رزرو جدید پس از ارسال')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment', verbose_name='نوبت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': '🔔 یادآوری تمدید',
                'verbose_name_plural': '🔔 یادآوری\u200cهای تمدید',
                'db_table': 'renewal_reminders',
                'ordering': ['days_remaining'],
            },
        ),
    ]
