# Generated by Django 5.1.4 on 2026-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contactmessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinkgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
