# Generated by Django 5.1.4 on 2026-09-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_teamsection_team_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsection',
            options={},
        ),
    ]
