# Generated by Django 5.1.4 on 2026-09-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_faqcategory_faqitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['order'], 'verbose_name': '📂 دسته\u200cبندی سوال', 'verbose_name_plural': '📂 دسته\u200cبندی\u200cهای سوالات'},
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landing.faqcategory', verbose_name='دسته\u200cبندی (تب)'),
        ),
    ]
