# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('query', models.CharField(db_index=True, max_length=200, verbose_name='عبارت جستجو')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نتایج')),
                ('category', models.CharField(blank=True, default='', help_text='مثلاً: businesses, services, posts', max_length=50, verbose_name='دسته\u200cبندی جستجو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '🔍 تاریخچه جستجو',
                'verbose_name_plural': '🔍 تاریخچه جستجوها',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['query'], name='search_hist_query_69a772_idx')],
            },
        ),
    ]
