# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('business', 'کسب\u200cوکار'), ('magazine', 'مجله بیو کلاب')], default='business', max_length=20, verbose_name='منبع')),
                ('caption', models.TextField(max_length=500, verbose_name='کپشن')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.servicecategory', verbose_name='دسته\u200cبندی اصلی')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subservice', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': '🔍 پست ویترین',
                'verbose_name_plural': '🔍 پست\u200cهای ویترین',
                'db_table': 'explore_posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='explore/posts/', verbose_name='تصویر')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='explore.explorepost', verbose_name='پست')),
            ],
            options={
                'verbose_name': '🖼️ تصویر پست',
                'verbose_name_plural': '🖼️ تصاویر پست',
                'db_table': 'post_images',
                'ordering': ['sort_order'],
            },
        ),
    ]
