# Generated by Django 5.1.4 on 2026-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_maintenance_modal_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='store_url',
            field=models.URLField(blank=True, default='https://app.beauclub.ir', verbose_name='لینک آپدیت'),
        ),
    ]
