# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.BigIntegerField(verbose_name='مبلغ تسویه (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال واریز'), ('completed', 'واریز شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('bank_sheba', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='businesses.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': '🏧 تسویه حساب',
                'verbose_name_plural': '🏧 تسویه حساب\u200cها',
                'db_table': 'settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('deposit', 'بیعانه'), ('full_payment', 'پرداخت کامل'), ('refund', 'استرداد'), ('settlement', 'تسویه')], max_length=20, verbose_name='نوع')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('app_fee', models.BigIntegerField(default=0, verbose_name='کمیسیون بیو کلاب (تومان)')),
                ('status', models.CharField(choices=[('blocked', 'بلوکه (در انتظار خدمت)'), ('settling', 'در حال تسویه'), ('settled', 'تسویه شده'), ('refunded', 'مسترد به مشتری'), ('failed', 'ناموفق')], default='blocked', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(default='zibal', max_length=50, verbose_name='درگاه پرداخت')),
                ('gateway_transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه تراکنش درگاه')),
                ('tracking_code', models.CharField(blank=True, default='', max_length=50, verbose_name='کد پیگیری')),
                ('ref_number', models.CharField(blank=True, default='', max_length=50, verbose_name='شماره ارجاع')),
                ('card_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره کارت')),
                ('card_bank', models.CharField(blank=True, default='', max_length=50, verbose_name='بانک کارت')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('estimated_settlement', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تخمینی تسویه')),
                ('refund_reason', models.TextField(blank=True, default='', verbose_name='دلیل استرداد')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='appointments.appointment', verbose_name='نوبت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': '💰 تراکنش',
                'verbose_name_plural': '💰 تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='transaction_busines_a6934e_idx'), models.Index(fields=['customer', 'status'], name='transaction_custome_159f06_idx')],
            },
        ),
    ]
