# Generated by Django 5.1.4 on 2026-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_status_1a84dc_idx',
            old_name='settle_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_busines_19d4fa_idx',
            old_name='settle_biz_status_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_settled_e0e193_idx',
            old_name='settle_settled_at_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_status_94cf9d_idx',
            old_name='tx_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_busines_9b0f77_idx',
            old_name='tx_biz_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_custome_fb8ec8_idx',
            old_name='tx_customer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_gateway_0e3856_idx',
            old_name='tx_gateway_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_settled_e53ee0_idx',
            old_name='tx_settled_at_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_trackin_c6d2ac_idx',
            old_name='tx_tracking_code_idx',
        ),
        migrations.AddField(
            model_name='settlement',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='دلیل رد'),
        ),
    ]
