# Generated by Django 5.1.4 on 2026-08-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': '📍 استان',
                'verbose_name_plural': '📍 استان\u200cها',
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': '🏙️ شهر',
                'verbose_name_plural': '🏙️ شهرها',
                'db_table': 'cities',
                'unique_together': {('province', 'slug')},
            },
        ),
    ]
