# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('categories', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آگهی')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('line_image', models.ImageField(upload_to='ads/line_rentals/', verbose_name='تصویر لاین')),
                ('collab_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'اجاره ثابت'), ('hourly', 'ساعتی')], max_length=20, verbose_name='نوع همکاری')),
                ('percent_salon', models.IntegerField(blank=True, null=True, verbose_name='سهم سالن (%)')),
                ('percent_partner', models.IntegerField(blank=True, null=True, verbose_name='سهم همکار (%)')),
                ('fixed_amount', models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ اجاره ثابت')),
                ('fixed_deposit', models.BigIntegerField(blank=True, null=True, verbose_name='رهن / ودیعه')),
                ('hourly_rate', models.BigIntegerField(blank=True, null=True, verbose_name='نرخ ساعتی')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('created_jalali', models.CharField(max_length=10, verbose_name='تاریخ ایجاد جلالی')),
                ('expires_jalali', models.CharField(max_length=10, verbose_name='تاریخ انقضای جلالی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_rentals', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.servicecategory', verbose_name='دسته\u200cبندی خدمات')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.subservice', verbose_name='زیرخدمت')),
            ],
            options={
                'verbose_name': '🏬 آگهی اجاره لاین',
                'verbose_name_plural': '🏬 آگهی\u200cهای اجاره لاین',
                'db_table': 'line_rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('service_image', models.ImageField(upload_to='ads/model_requests/', verbose_name='تصویر خدمت')),
                ('cost_type', models.CharField(choices=[('paid', 'با هزینه'), ('material_cost', 'با هزینه مواد'), ('free', 'رایگان')], default='material_cost', max_length=20, verbose_name='نوع هزینه')),
                ('discount', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='فوری')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('created_jalali', models.CharField(max_length=10, verbose_name='تاریخ ایجاد جلالی')),
                ('expires_jalali', models.CharField(max_length=10, verbose_name='تاریخ انقضای جلالی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_requests', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': '👤 درخواست مدل',
                'verbose_name_plural': '👤 درخواست\u200cهای مدل',
                'db_table': 'model_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
