# Generated by Django 5.1.4 on 2026-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_linerental_location_modelrequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linerental',
            name='line_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/line_rentals/', verbose_name='تصویر لاین'),
        ),
        migrations.AlterField(
            model_name='modelrequest',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/model_requests/', verbose_name='تصویر خدمت'),
        ),
    ]
