# Generated by Django 5.1.4 on 2026-09-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_tic_user_id_eb143a_idx',
            old_name='ticket_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_tic_status_c8e2c5_idx',
            old_name='ticket_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_tic_status_627203_idx',
            old_name='ticket_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_tic_user_id_057736_idx',
            old_name='ticket_user_status_idx',
        ),
    ]
