# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, default='', max_length=300, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(upload_to='portfolios/covers/', verbose_name='تصویر کاور')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.servicecategory', verbose_name='دسته\u200cبندی')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.subservice', verbose_name='زیرخدمت')),
            ],
            options={
                'verbose_name': '🖼️ نمونه\u200cکار',
                'verbose_name_plural': '🖼️ نمونه\u200cکارها',
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='portfolios/images/', verbose_name='تصویر')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolios.portfolio', verbose_name='نمونه\u200cکار')),
            ],
            options={
                'verbose_name': '📷 تصویر نمونه\u200cکار',
                'verbose_name_plural': '📷 تصاویر نمونه\u200cکار',
                'db_table': 'portfolio_images',
                'ordering': ['sort_order'],
            },
        ),
    ]
