# Generated by Django 5.1.4 on 2026-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام کمپین')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('ended', 'پایان یافته')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('budget', models.BigIntegerField(default=0, verbose_name='بودجه (تومان)')),
                ('spent', models.BigIntegerField(default=0, verbose_name='مبلغ خرج شده (تومان)')),
                ('impressions', models.IntegerField(default=0, verbose_name='تعداد نمایش')),
                ('clicks', models.IntegerField(default=0, verbose_name='تعداد کلیک')),
            ],
            options={
                'verbose_name': '📊 کمپین تبلیغاتی',
                'verbose_name_plural': '📊 کمپین\u200cهای تبلیغاتی',
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
