# Generated by Django 5.1.4 on 2026-09-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_management', '0001_initial'),
        ('businesses', '0004_add_suspension_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='توضیحات (زیرعنوان)')),
                ('image', models.ImageField(upload_to='ads/banners/%Y/%m/', verbose_name='تصویر بنر')),
                ('custom_url', models.URLField(blank=True, default='', help_text='اگر کسب\u200cوکار انتخاب نشود، می\u200cتوانید لینک دلخواه (مثل لینک ثبت\u200cنام) وارد کنید.', verbose_name='لینک دلخواه')),
                ('badge', models.CharField(blank=True, default='', help_text='مثال: ۲۰٪ تخفیف، جدید، پیشنهادات ویژه', max_length=50, verbose_name='متن بج (اختیاری)')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('business', models.ForeignKey(blank=True, help_text='در صورت انتخاب، کلیک روی بنر کاربر را به پروفایل این کسب\u200cوکار می\u200cبرد.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_banners', to='businesses.business', verbose_name='کسب\u200cوکار مقصد')),
            ],
            options={
                'verbose_name': '🖼️ بنر اسلایدر',
                'verbose_name_plural': '🖼️ بنرهای اسلایدر',
                'db_table': 'ad_banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
