# Generated by Django 5.1.4 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_management', '0002_adbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(upload_to='promotions/slides/%Y/%m/', verbose_name='تصویر بنر'),
        ),
    ]
