# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, default='', max_length=300, verbose_name='متن نظر')),
                ('tags', models.JSONField(default=list, verbose_name='تگ\u200cها')),
                ('reply', models.TextField(blank=True, default='', verbose_name='پاسخ سالن')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment', verbose_name='نوبت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': '⭐ نظر',
                'verbose_name_plural': '⭐ نظرات',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('appointment', 'customer')},
            },
        ),
    ]
