# Generated by Django 5.1.4 on 2026-08-12 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('jy', models.IntegerField(verbose_name='سال جلالی')),
                ('jm', models.IntegerField(verbose_name='ماه جلالی')),
                ('jd', models.IntegerField(verbose_name='روز جلالی')),
                ('date_key', models.CharField(max_length=10, verbose_name='کلید تاریخ')),
                ('time_slot', models.TimeField(verbose_name='ساعت نوبت')),
                ('status', models.CharField(choices=[('reserved', 'رزرو شده'), ('done', 'انجام شده'), ('cancelled_by_salon', 'لغو توسط سالن'), ('cancelled_by_customer', 'لغو توسط مشتری')], db_index=True, default='reserved', max_length=30, verbose_name='وضعیت')),
                ('verification_code', models.CharField(blank=True, default='', max_length=4, verbose_name='کد تایید ۴ رقمی')),
                ('is_trust_based', models.BooleanField(default=False, verbose_name='اعتماد به سالن')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='دلیل لغو')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('total_price', models.BigIntegerField(verbose_name='قیمت کل (تومان)')),
                ('deposit_amount', models.BigIntegerField(default=0, verbose_name='مبلغ بیعانه (تومان)')),
                ('remaining_amount', models.BigIntegerField(default=0, verbose_name='مبلغ باقی\u200cمانده (تومان)')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شده')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال یادآوری')),
                ('has_review', models.BooleanField(default=False, verbose_name='نظر ثبت شده')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': '📅 نوبت',
                'verbose_name_plural': '📅 نوبت\u200cها',
                'db_table': 'appointments',
                'ordering': ['-jy', '-jm', '-jd', 'time_slot'],
                'indexes': [models.Index(fields=['business', 'date_key'], name='appointment_busines_719d5c_idx'), models.Index(fields=['customer', 'status'], name='appointment_custome_48801d_idx')],
            },
        ),
    ]
