# Generated by Django 5.1.4 on 2026-09-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_date_ke_59e4fb_idx',
            old_name='apt_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_busines_154213_idx',
            old_name='apt_biz_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_custome_916d5e_idx',
            old_name='apt_customer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_status_5393fc_idx',
            old_name='apt_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_jy_d41f6a_idx',
            old_name='apt_jalali_datetime_idx',
        ),
    ]
