# Generated by Django 5.1.4 on 2026-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_apt_date_status_idx_appointment_date_ke_59e4fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام خدمت'),
        ),
    ]
