# Generated by Django 5.1.4 on 2026-08-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('jy', models.IntegerField(verbose_name='سال جلالی')),
                ('jm', models.IntegerField(verbose_name='ماه جلالی (1-12)')),
                ('jd', models.IntegerField(verbose_name='روز جلالی')),
                ('date_key', models.CharField(max_length=10, verbose_name='کلید تاریخ')),
                ('work_start', models.TimeField(verbose_name='ساعت شروع')),
                ('work_end', models.TimeField(verbose_name='ساعت پایان')),
                ('slot_duration', models.IntegerField(verbose_name='مدت هر نوبت (دقیقه)')),
                ('breaks', models.JSONField(default=list, help_text='[{start: "13:00", end: "14:00"}, ...]', verbose_name='استراحت\u200cها')),
                ('slot_count', models.IntegerField(default=0, verbose_name='تعداد اسلات\u200cها')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='businesses.business', verbose_name='کسب\u200cوکار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': '🕐 زمان\u200cبندی خدمت',
                'verbose_name_plural': '🕐 زمان\u200cبندی\u200cهای خدمات',
                'db_table': 'service_schedules',
                'ordering': ['jy', 'jm', 'jd'],
                'unique_together': {('service', 'date_key')},
            },
        ),
    ]
