# Generated by Django 5.1.4 on 2026-07-26 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('otp_login', 'OTP ورود'), ('otp_change_phone', 'OTP تغییر شماره'), ('booking_confirmed', 'تایید رزرو'), ('booking_reminder', 'یادآوری نوبت'), ('booking_cancelled', 'لغو نوبت'), ('payment_success', 'پرداخت موفق'), ('refund_completed', 'استرداد وجه'), ('business_approved', 'تایید کسب\u200cوکار'), ('business_rejected', 'رد کسب\u200cوکار'), ('verification_code', 'کد تایید نوبت')], max_length=30, unique=True, verbose_name='نوع قالب')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('provider_template_id', models.CharField(help_text='مثلاً template_id کاوه\u200cنگار', max_length=100, verbose_name='شناسه قالب در سرویس\u200cدهنده')),
                ('pattern', models.TextField(help_text='مثلاً: کد تایید شما: {code}', verbose_name='متن قالب (با متغیر)')),
                ('variables', models.JSONField(blank=True, default=list, help_text='لیست متغیرها: ["code", "name"]', verbose_name='متغیرها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': '📝 قالب پیامک',
                'verbose_name_plural': '📝 قالب\u200cهای پیامک',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'اندروید'), ('ios', 'آی\u200cاو\u200cاس'), ('web', 'وب')], max_length=10, verbose_name='پلتفرم')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='توکن دستگاه (FCM/APNs)')),
                ('device_name', models.CharField(blank=True, default='', max_length=200, verbose_name='نام دستگاه')),
                ('app_version', models.CharField(blank=True, default='', max_length=20, verbose_name='نسخه اپلیکیشن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '📱 دستگاه Push',
                'verbose_name_plural': '📱 دستگاه\u200cهای Push',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_confirmed', 'تایید رزرو'), ('booking_reminder', 'یادآوری نوبت'), ('booking_cancelled', 'لغو نوبت'), ('booking_done', 'انجام خدمت'), ('payment_success', 'پرداخت موفق'), ('payment_refunded', 'استرداد وجه'), ('settlement_completed', 'تسویه تکمیل شد'), ('new_review', 'نظر جدید'), ('business_approved', 'تایید کسب\u200cوکار'), ('business_rejected', 'رد کسب\u200cوکار'), ('system', 'سیستمی'), ('promo', 'تبلیغاتی')], max_length=30, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('data', models.JSONField(blank=True, default=dict, help_text='مثلاً appointment_id یا deep_link', verbose_name='داده\u200cهای تکمیلی (JSON)')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_pushed', models.BooleanField(default=False, verbose_name='Push ارسال شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خوانده شدن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': '🔔 اعلان',
                'verbose_name_plural': '🔔 اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_827754_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='متن پیامک')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='متغیرهای استفاده شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه پیام در سرویس\u200cدهنده')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='هزینه (ریال)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.smstemplate', verbose_name='قالب')),
            ],
            options={
                'verbose_name': '📨 لاگ پیامک',
                'verbose_name_plural': '📨 لاگ پیامک\u200cها',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['phone', '-sent_at'], name='notificatio_phone_50b0b4_idx'), models.Index(fields=['status', '-sent_at'], name='notificatio_status_571b03_idx')],
            },
        ),
    ]
