# Generated by Django 5.1.4 on 2026-09-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_type_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_read_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='smslog',
            name='smslog_user_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='smslog',
            name='smslog_template_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='smslog',
            name='smslog_created_idx',
        ),
    ]
