# Generated by Django 5.1.4 on 2026-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_notif_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'تایید رزرو'), ('booking_reminder', 'یادآوری نوبت'), ('booking_cancelled', 'لغو نوبت'), ('booking_done', 'انجام خدمت'), ('payment_success', 'پرداخت موفق'), ('payment_refunded', 'استرداد وجه'), ('settlement_completed', 'تسویه تکمیل شد'), ('new_review', 'نظر جدید'), ('business_approved', 'تایید کسب\u200cوکار'), ('business_rejected', 'رد کسب\u200cوکار'), ('system', 'سیستمی'), ('promo', 'تبلیغاتی'), ('business_suspended', 'تعلیق کسب\u200cوکار')], max_length=30, verbose_name='نوع اعلان'),
        ),
    ]
